Fixes undefined method each_pair
There is a bug in the Travis gem (at least as recent as 1.8.8) that causes it to fail loading the log. The below overrides solve the problem.

/home/ci/bundle/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load': undefined method `each_pair' for #<String...

Found this workaround here: https://github.com/travis-ci/travis.rb/issues/578#issuecomment-368142083